
version: '3'

services:
  starter:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: starter
    env_file:  ./.env
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app"
      - "reserved:/usr/src/app/node_modules"
    stdin_open: true
    tty: true  
volumes:
  reserved:    